### ISSUE TITLE
请问可以发给我一份数据吗？这个数据开源吗？

### ISSUE THREAD

**Issue by mozhuqin** [llmir/MultitaskOCTA#1]

**Comment by llmir** [comment]
你好，邮件没有发错，这是林立的邮箱。紧急事情请发短信或者打电话到15521000952提醒我查看邮箱，谢谢！

**Comment by llmir** [comment]
Hi, thank you for your attention. Now I have uploaded the datasets ([AliDrive](https://www.aliyundrive.com/s/eHpKveH3jfH) and [GoogleDrive](https://drive.google.com/drive/folders/1PIlDncAQUCG6-ffINujYOgNSJHdqLVcu?usp=sharing)). If you find it helpful, please cite our relevant papers. Thanks again.

**Comment by llmir** [comment]
> Hi, thank you for your attention. Now I have uploaded the datasets ([AliDrive](https://www.aliyundrive.com/s/eHpKveH3jfH) and [GoogleDrive](https://drive.google.com/drive/folders/1PIlDncAQUCG6-ffINujYOgNSJHdqLVcu?usp=sharing)). If you find it helpful, please cite our relevant papers. Thanks again.
